# **************************************
# * Parameters for metannotate pipeline *
# **************************************

# List of files
list_files: "/home/aschick/projects/arrieta/list_files_test.txt"

# Path to sequences
path: "/home/aschick/projects/arrieta/metqc/data/bmtagger/"

# Path suffix for forward reads
for: "_bmtagged_1.fastq"
# Path suffic for reverse reads
rev: "_bmtagged_2.fastq"

# Location of nucleotide database
nuc_db: "/home/aschick/refs/humann2/chocophlan"
# Location os protein database
prot_db: "home/aschick/refs/humann2/uniref"
