# **************************************
# * Parameters for metannotate pipeline *
# **************************************

# List of files
#list_files: "/bulk/IMCshared_bulk/sycuro_shared_projects/Davide_TS/HUMAnN/metannotate_20210915/utils/list_files.txt"
list_files: "/bulk/IMCshared_bulk/kevin/IMC_shotgun_analysis/Project_10041/10041_Steven_Yip_and_Pinaki_Bose/sample_names_list_10041-YB_no_controls.txt"

# Path to sequences
path: "/bulk/IMCshared_bulk/kevin/IMC_shotgun_analysis/Project_10041/10041_Steven_Yip_and_Pinaki_Bose/analysis/cleaned_reads_metqc/bmtagger/"

# Path to already run metahphlan output files
metaphlan_results_path: "/bulk/IMCshared_bulk/kevin/IMC_shotgun_analysis/Project_10041/10041_Steven_Yip_and_Pinaki_Bose/analysis/metaphlan4_gtdb/metaphlan/{sample}_profile.txt"

# output directory
output_dir: "/bulk/IMCshared_bulk/kevin/IMC_shotgun_analysis/Project_10041/10041_Steven_Yip_and_Pinaki_Bose/analysis/metannotate"

# Are reads paired?
paired: TRUE

# Number of threads to use humann3.
num_threads: 8

# If paired-end reads, suffix for forward reads
for: "_bmtagged_1.fastq"
# If paired-end reads, suffix for reverse reads
rev: "_bmtagged_2.fastq"

# If unpaired reads, suffix for reads
suff: "_bmt_merged_ELC_trimmed_filtered.fastq"

# Location of nucleotide database
nuc_db: "/bulk/IMCshared_bulk/shared/dbs/humann_dbs_3.1/chocophlan"

# Location os protein database
prot_db: "/bulk/IMCshared_bulk/shared/dbs/humann_dbs_3.1/uniref"

# Location of maping files

uniref90_name: "/bulk/IMCshared_bulk/shared/dbs/humann_dbs_3.1/utility_mapping/map_uniref90_name.txt.bz2"
eggnog_uniref90: "/bulk/IMCshared_bulk/shared/dbs/humann_dbs_3.1/utility_mapping/map_eggnog_uniref90.txt.gz"  
ko_uniref90: "/bulk/IMCshared_bulk/shared/dbs/humann_dbs_3.1/utility_mapping/map_ko_uniref90.txt.gz"        
eggnog_name: "/bulk/IMCshared_bulk/shared/dbs/humann_dbs_3.1/utility_mapping/map_eggnog_name.txt.gz"       
ko_name: "/bulk/IMCshared_bulk/shared/dbs/humann_dbs_3.1/utility_mapping/map_ko_name.txt.gz"      
uniref_name: "/bulk/IMCshared_bulk/shared/dbs/humann_dbs_3.1/utility_mapping/map_uniref90_name.txt.bz2"
